# Generated by Django 2.2.3 on 2019-08-17 10:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'True'), (0, 'False')])),
                ('parent_id', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('marka', models.CharField(max_length=30)),
                ('cinsiyet', models.IntegerField(choices=[(1, 'ERKEK'), (0, 'BAYAN')])),
                ('kadran_tipi', models.CharField(blank=True, max_length=15)),
                ('kadran_rengi', models.IntegerField(blank=True, choices=[(11, 'Altın Rengi'), (10, 'Metalik Gri'), (9, 'Rose Gold'), (8, 'Siyah'), (7, 'Kahverengi'), (6, 'Mavi'), (5, 'Lacivert'), (4, 'BAYAN'), (3, 'Füme'), (2, 'Bakır'), (1, 'Turuncu'), (0, 'Yeşil')])),
                ('kasa_capi', models.IntegerField(blank=True)),
                ('kasa_rengi', models.IntegerField(choices=[(11, 'Altın Rengi'), (10, 'Metalik Gri'), (9, 'Rose Gold'), (8, 'Siyah'), (7, 'Kahverengi'), (6, 'Mavi'), (5, 'Lacivert'), (4, 'BAYAN'), (3, 'Füme'), (2, 'Bakır'), (1, 'Turuncu'), (0, 'Yeşil')])),
                ('cam', models.CharField(max_length=15)),
                ('kayis_rengi', models.IntegerField(blank=True, choices=[(11, 'Altın Rengi'), (10, 'Metalik Gri'), (9, 'Rose Gold'), (8, 'Siyah'), (7, 'Kahverengi'), (6, 'Mavi'), (5, 'Lacivert'), (4, 'BAYAN'), (3, 'Füme'), (2, 'Bakır'), (1, 'Turuncu'), (0, 'Yeşil')])),
                ('kayis_tipi', models.CharField(blank=True, max_length=15)),
                ('su', models.IntegerField(choices=[(5, 'Yok'), (4, '5 ATM'), (3, '10 ATM'), (2, '15 ATM'), (1, '30 ATM'), (0, '50 ATM')])),
                ('kronometre', models.IntegerField(choices=[(1, 'Var'), (0, 'Yok')])),
                ('takvim', models.IntegerField(choices=[(1, 'Var'), (0, 'Yok')])),
                ('alarm', models.IntegerField(choices=[(1, 'Var'), (0, 'Yok')])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.FloatField()),
                ('amaunt', models.IntegerField()),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'True'), (0, 'False')])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
    ]
