# Generated by Django 2.2.3 on 2019-08-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipaddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipname',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipphone',
            new_name='sname',
        ),
    ]
